### ISSUE TITLE
Script not recognised

### ISSUE THREAD

**Issue by ElVicente** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#10]
Hi, I tried to install your script following the instructions but it seems not to be recognised. Nothing new for the launchpad pro mk3 on the controller menu... :(

I'm on win10 and bitwig 4.0.8 by the way...

**Comment by weskoop** [comment]
1) Ensure the Download is unzipped into the folder specified in your Bitwig Preferences > Settings > Locations > My Controller Scripts > ...
2) Restart Bitwig
3) Select it from the list manually

I did all of the development on 4.1.x, I don't think there is anything that would stop it from working on 4.0.x

**Comment by weskoop** [comment]
Also make sure you are using the latest compiled download:

https://github.com/weskoop/Launchpad-Pro-Mk3-for-Bitwig/releases/download/v0.69/Launchpad-Pro-Mk3-for-Bitwig_0.69.zip

**Comment by weskoop** [comment]
I think i see the issue, It's the API version set in the main `.control.js` file. Setting line 21 to `loadAPI(12);` allows it to show up. 

I will package a new version tonight.

**Comment by weskoop** [comment]
Fixed in 805df2a04d67168cf446cd630db6cd740fd9a38c

**Comment by ElVicente** [comment]
It's working now ! Thank you :)
