### ISSUE TITLE
Toggle for Debug Messages

### ISSUE THREAD

**Issue by weskoop** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#11]
Add a Setting Toggle for Debug messages to the console.

**Comment by Fannon** [comment]
If this takes too much work, I'm not sure it would be worth the efforts.
The console is hidden anyway and when you open it you actually want to see the debug messages.
Not sure if this has any noticable impact on performance as well.

**Comment by weskoop** [comment]
Yeah this makes sense. Thanks for saving me the time. haha
