### ISSUE TITLE
Print to Clip

### ISSUE THREAD

**Issue by weskoop** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#18]
Pure Sysex, then the Script would need to handle translation into an actual clip.

Not a small undertaking.

To get start this toggles the Print to MIDI button on the launchpad:

Enable (Midi Clip slot selected)
08:29:14.696	To Launchpad Pro MK3 LPProMK3 DAW	SysEx		Focusrite / Novation 9 bytes	F0 00 20 29 02 0E 18 01 F7
08:29:14.697	To Launchpad Pro MK3 LPProMK3 DAW	Control	1	105	1
08:29:14.697	To Launchpad Pro MK3 LPProMK3 DAW	Control	1	106	16

Disable (Midi Clip Slot de-selected):
08:29:00.691	To Launchpad Pro MK3 LPProMK3 DAW	SysEx		Focusrite / Novation 9 bytes	F0 00 20 29 02 0E 18 00 F7
08:29:00.696	To Launchpad Pro MK3 LPProMK3 DAW	Control	1	105	76
08:29:00.696	To Launchpad Pro MK3 LPProMK3 DAW	Control	1	106	1

**Comment by weskoop** [comment]
Empty Sequence (Track 2):
08:31:47.761	From Launchpad Pro MK3 LPProMK3 DAW	SysEx		Focusrite / Novation 20 bytes	F0 00 20 29 02 0E 03 01 00 00 00 00 00 00 00 00 04 01 01 F7
08:31:47.772	From Launchpad Pro MK3 LPProMK3 DAW	SysEx		Focusrite / Novation 22 bytes	F0 00 20 29 02 0E 03 02 00 00 00 00 00 00 00 01 04 01 00 1F 20 F7
08:31:47.772	From Launchpad Pro MK3 LPProMK3 DAW	SysEx		Focusrite / Novation 27 bytes	F0 00 20 29 02 0E 03 03 00 00 00 00 00 00 00 02 04 01 0F 0F 04 01 0D 09 01 02 F7
08:31:47.799	To Launchpad Pro MK3 LPProMK3 DAW	Note On	1	66	16

Track 3:
08:32:04.085	From Launchpad Pro MK3 LPProMK3 DAW	SysEx		Focusrite / Novation 20 bytes	F0 00 20 29 02 0E 03 01 00 00 00 00 00 00 00 00 04 02 01 F7
08:32:04.097	From Launchpad Pro MK3 LPProMK3 DAW	SysEx		Focusrite / Novation 22 bytes	F0 00 20 29 02 0E 03 02 00 00 00 00 00 00 00 01 04 02 00 1F 20 F7
08:32:04.097	From Launchpad Pro MK3 LPProMK3 DAW	SysEx		Focusrite / Novation 27 bytes	F0 00 20 29 02 0E 03 03 00 00 00 00 00 00 00 02 04 02 0F 0F 04 01 0D 09 01 02 F7

**Comment by weskoop** [comment]
Section  9.11 Print to Clip

> Sequencer patterns may be instantly transferred from Launchpad Pro to Ableton Live and placed in clip slots, with no need to record them. Print to Clip is extremely useful for taking your ideas from the sequencer into more complete tracks within Ableton Live.
> This function is accessed via the Print to Clip button.
> When you have created a sequence with the Launchpad Pro that you would like to transfer to Ableton Live, select a clip slot in Live by clicking it with your mouse, then press Print to Clip on Launchpad Pro. The current pattern or pattern chain for the selected track will be transferred to Live.
> 9.11.A - A selected 9.11.B – The same empty clip slot clip slot, now filled after pressing Print
> to Clip
> Alternatively, a clip slot in may be selected using Launchpad Pro by navigating to Session View, holding shift, and pressing a pad on the 8x8 grid.
> If you had an empty clip slot selected, the printed pattern will now be in that slot as a clip. If you press Print to Clip while an occupied clip slot is selected, the sequencer pattern will be printed to the next empty clip slot below. This enables you to print a pattern multiple times without overwriting any clips.
> You can also use Print to Clip in Patterns view. To do so, hold Print to Clip and press a track select button. Notice that the track buttons will pulse while Print to Clip is held. The currently selected pattern or pattern chain on chosen track will be transferred to Ableton Live.
> If you are using Ableton Live Lite and all 8 available clip slots for a track are full, the Print to Clip button will become unlit to indicate that there are no available clip slots to transfer to.

**Comment by blueneogeo** [comment]
Amazing if you guys can add this.

**Comment by weskoop** [comment]
Unfortunately have run low on time for this project at the moment, should that lighten up anytime, i may dip back in. But happy to review pull requests for anyone that wants to decode this functionality :)

**Comment by weskoop** [comment]
Thanks for your notes, I really appreciate you putting in the time to debug; Bitwig 5.0+ include native support for the LaunchPad Pro Mk3. This project is no longer supported.
