### ISSUE TITLE
Momentary Clip Launching

### ISSUE THREAD

**Issue by weskoop** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#20]
> New control surface API to launch clips with specific options. In the APC40mkII and Launchpad Pro scripts, you can:
> - Hold shift to immediately launch a clip or a scene
> - Release the clip or scene button while holding shift, to return immediately to last playing clip(s)

Momentary clips would be awesome, but updating the API version will exclude old versions of Bitwig. At a minimum we'll push one more release without this, but then we make make future versions require 4.2, or we maintain 2 versions, less into that.

We also use Shift + Grid for Selecting a slot, so this may need to be an optional thing, or Select only works on empty slots.

We'll look into all of this later when 4.2 is out of beta.

**Comment by mwozniczak** [comment]
> but then we make make future versions require 4.2

I'm relatively new to Bitwig's API, but wouldn't either try-catching, or something like

```javascript
const some_bitwig_functionality = some_bitwig_functionality|a_stub_that_does_nothing
```
not work in this situation?

**Comment by weskoop** [comment]
I'm pretty sure the momentary clip launching is only available in the 4.2+ version of the Controller API. In any controller script, you need to declare the minimum API version at the beginning of the script. Is not the worst situation, since users on the old version can always use 1.0

**Comment by mwozniczak** [comment]
@weskoop what would happen if you declared a lower version, and then tried to use something from the higher version? i mean, on bitwig that supports the higher version? would it reject it, or let it through? because if the latter, then try-catching or stubbing might be a way of supporting both the lower versions, and the new functionality

**Comment by weskoop** [comment]
I'm open to reviewing a PR if you'd like to try, but don't have a ton of time right now to expand this. The other issue is that the typescript lib I'm using is still at API 12, so we may need to augment that as well.

**Comment by mwozniczak** [comment]
understandable, once I'm back from my vacation i'd be glad to give it a go!

**Comment by weskoop** [comment]
Thanks for your notes, I really appreciate you putting in the time to debug; Bitwig 5.0+ include native support for the LaunchPad Pro Mk3. This project is no longer supported.
