### ISSUE TITLE
when selecting an empty clip, is there an option to have the track arm itself and cue up recording same as with armed tracks?

### ISSUE THREAD

**Issue by mwozniczak** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#21]
could have sworn it worked like that when i first tried the script. did i imagine it? did i accidentally disable it somehow?

either way, being able to launch recording like that would not only speed things up (for me at least), but also prevent errors

**Comment by weskoop** [comment]
I don't believe it ever worked like that. I think the idea of arming the track deliberately is the safest way to prevent errors, If you want too live on the edge, you could just have all your tracks armed and ready to go. Shift + Cell Only selects a cell. I think in a future update for 4.2+, we may add to option for momentary playback.
