### ISSUE TITLE
Have the device sliders mirror the colors of  the presets in the device presets page

### ISSUE THREAD

**Issue by blueneogeo** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#24]
Bitwig presets each have a color, and making the sliders adopt this color would make it much easier to pick the correct slider.

**Comment by weskoop** [comment]
This code is actually done, but a new release has not been generated, if you build the project from source, you can get the "Rainbow Faders" options, see issue #5 for details.

I will try to find some time to make a 1.1 release this week with the option, but feel free to pull the code down and build it if you want it quicker.

**Comment by blueneogeo** [comment]
Thank you!

**Comment by weskoop** [comment]
Heads up @blueneogeo! 🎚️‼️

https://github.com/weskoop/Launchpad-Pro-Mk3-for-Bitwig/releases/tag/v1.1

**Comment by blueneogeo** [comment]
Fantastic!
