### ISSUE TITLE
Patterns knob lights up green in Session mode

### ISSUE THREAD

**Issue by questionaires** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#25]
When booting up Bitwig with launchpad connected , adding an instrument and pressing device knob to modify its parameters will lights up the patterns knob in green in session mode. Pressing the sends button will make the patterns knob light in white in session mode.

It will happen from within session mode and note mode and chord mode and sequencer mode. But the patterns button lighten in green or white  is only shown when returning to session mode then.

Hopefully it can be corrected,

Thanks,

Great script by the way really loving it.

**Comment by weskoop** [comment]
I tried to recreate this, but i'm not entirely following the issue, and I'm not seeing any issues with the sampler. 

- Can you clarify and offer some steps to recreate?
- When you say "Knobs" do you mean buttons? (There are no knobs on the LaunchPad)
- What version of the script and bitwig?

**Comment by questionaires** [comment]
Hello weskoop, Yes I can give you how to recreate and describe it how to: Load up bitwig (in my case version 4.4 and your script 1.1) and latest Launchpad firmware.Add an instrument Go to session modePress the “device” button to change some values of that instrumentGo back to session mode in the case you were permanent in the device page.Now the last chosen pages buttons (patterns, steps, pattern settings, velocity, probability) will be clearly light green or another color. This in my opinion should not be the case the clear light should be resseted to dimmed white as with all the other buttons. So somehow the light is not being ressetted to the initial value of session mode. You are right I said knobs but I mean buttons. Thanks for having a look into this. Regards,Wilfred Sent from Mail for Windows From: wes koopSent: Sunday, October 16, 2022 12:25 AMTo: weskoop/Launchpad-Pro-Mk3-for-BitwigCc: questionaires; AuthorSubject: Re: [weskoop/Launchpad-Pro-Mk3-for-Bitwig] Patterns knob lights up green in Session mode (Issue #25) I tried to recreate this, but i'm not entirely following the issue, and I'm not seeing any issues with the sampler.Can you clarify and offer some steps to recreate?When you say "Knobs" do you mean buttons? (There are no knobs on the LaunchPad)What version of the script and bitwig?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by questionaires** [comment]
Hello Weskoop, is there any news on this? Did you manage to recreate this following my steps?

**Comment by weskoop** [comment]
> Hello Weskoop, is there any news on this? Did you manage to recreate this following my steps?

Sorry I haven't been able to sit down and test, I hope to get a look in the next couple weeks.

**Comment by weskoop** [comment]
I can't recreate this issue, I've followed the instructions with multiple devices. I don't see any Green LEDs, the device page is Magenta (Not Green, Volume is green), the other pages are fine, this workflow works in both rainbow mode and not. 

I'm sorry, I'm not sure what else i can do on my end. I'm going to close this one unless someone can provide a video, or another way to reproduce.

If anyone else has this issue, please add a reply.

**Comment by questionaires** [comment]
Hello Weskoop thanks for trying to understand my limited englisch, i have attached a video where it is hopefully more clear.

https://user-images.githubusercontent.com/91179129/210380366-0d9a70a4-5af6-4331-b120-f37f0d5975de.mp4

**Comment by weskoop** [comment]
I see it!

**Comment by questionaires** [comment]
Yoohooo!!!! Thank you that was a hard hit to explain..   :-)

Really what a nice peace of work it becomes!

**Comment by questionaires** [comment]
By the way the same applies when you have more then 2 sends to choose from. In that case you choose which sends channel you select by pushing the same buttons for adjusting the individual track levels. The same buttons will light up green aswell.

**Comment by weskoop** [comment]
Thanks for your notes, I really appreciate you putting in the time to debug; Bitwig 5.0+ include native support for the LaunchPad Pro Mk3. This project is no longer supported.
