### ISSUE TITLE
Orange and red track colours all have the same redish colour as clips and as track colours

### ISSUE THREAD

**Issue by questionaires** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#26]
No matter what orange or red colour you give to a track they all appear in the same red colour it seems there is no slight contrast between them, and difficult to distinguish between them. The same for the green colours.

Is there somehow a way to add some more contrast?

**Comment by weskoop** [comment]
Unfortunately, there is a limited palette of colours. You can see the list here. We try to match as close as we can, but there is only so many reds/oranges/etc. 

https://fael-downloads-prod.focusrite.com/customer/prod/s3fs-public/downloads/LPP3_prog_ref_guide_200415.pdf

**Comment by questionaires** [comment]
Too bad! However not a big issue 😊 Sent from Mail for Windows From: wes koopSent: Sunday, October 16, 2022 12:14 AMTo: weskoop/Launchpad-Pro-Mk3-for-BitwigCc: questionaires; AuthorSubject: Re: [weskoop/Launchpad-Pro-Mk3-for-Bitwig] Orange and red track colours all have the same redish colour as clips and as track colours (Issue #26) Unfortunately, there is a limited palette of colours. You can see the list here. We try to match as close as we can, but there is only so many reds/oranges/etc.https://fael-downloads-prod.focusrite.com/customer/prod/s3fs-public/downloads/LPP3_prog_ref_guide_200415.pdf—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
