### ISSUE TITLE
Drum mode doesn't enable if the drum instrument has any note FX devices in front of it

### ISSUE THREAD

**Issue by mwozniczak** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#27]
I suspect this is because enabling the drum mode takes into consideration the first _device_ on a track, rather than first _actual instrument_

Also quick aside, is there any way of having the drum mode be toggleable regardless of whether something's a bitwig drum machine? Would be real useful e.g. with Kontakt setups

**Comment by weskoop** [comment]
Thanks, found a fix.

**Comment by weskoop** [comment]
Will be in the next release, you can also build from source, see the instructions in the readme.

Thanks again, sorry for the delay.
