### ISSUE TITLE
Scale and key not preserved when Launchpad's reconnected, or Bitwig restarts

### ISSUE THREAD

**Issue by mwozniczak** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#28]
I noticed that if you set anything in the shift+note mode (scale, key and layout changer), what you've input there is not preserved. Which is super tedious to have to remember, and set, every time you launch your project.

I actually asked Novation people if Launchpad provides any functionality that would help out with that, and this is what they gave me (regrettably, i have to post a screenshot, because the original table is formatted in some weird way which github's markdown parser absolutely despises):

![image](https://user-images.githubusercontent.com/14187903/201471593-cedb1bfa-ef96-4c3e-bce1-62b77313b322.png)

Hopefully this is helpful and/or useful!

**Comment by weskoop** [comment]
I'll look into this (at some point, time has been extremely limited as you can see from my reply times).

Can you just upload the original PDF here? Does it contain any additional information or context?

Thanks for opening an issue.

**Comment by weskoop** [comment]
I'm also not 100% sure how i would save this syses dump with the Bitwig project, and then load it. If we had a corresponding device, we could do it there, but that's not going to happen. While we can get a dump in the session, and into memory, i have no way to adding that to a bitwig project and then detecting the controller and running the command. If there is a way, it's a bit beyond me at the moment.

This thread covers a similar use-case
https://www.kvraudio.com/forum/viewtopic.php?t=409829&start=15

You might just have to save corresponding settings for the non-session modes into the Projects on the Launchpad themselves.

See section 9.12.1 (Saving your Sequencer Project) of the manual, "A saved Project also stores the Note/Chord mode settings, as well as all Custom Mode Master MIDI Channels."

**Comment by weskoop** [comment]
Thanks for your notes, I really appreciate you putting in the time to debug; Bitwig 5.0+ include native support for the LaunchPad Pro Mk3. This project is no longer supported.
