### ISSUE TITLE
Question: is this relevant for Bitwig 5 (with the Bitwig native script)?

### ISSUE THREAD

**Issue by nodens** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#30]
Hi there,

new Bitwig user here, and I'm wondering if this script is still relevant now that Bitwig ships with a native script for LP Pro MK3.

some stuff seems to exists in Bitwig implementation and not here, like using shift for momentary clip lanching. Is there anything else ?

Mostly curious.

Thanks !

**Comment by weskoop** [comment]
I haven't played around much with 5.0 or the new built-in script yet. I'm not sure how they match up feature for feature.

This project was created to fill the space since bigwig and notation didn't provide any support; now that it's official, i'm not sure i will be putting much more time into this one.

cheers!

**Comment by DaKingof** [comment]
I think they took this script and expanded on it. It has the same 'bugs' it seems.

When set to 'arranger', the buttons on the right should take on the functionality the buttons on the bottom have in chord/note when set to 'mix'. Currently, the buttons on the bottom stay functional in both when set to chord/note but behave in an unexpected way when 'arranger' is set.

These are the messages I am getting when hitting these buttons when I am in mix/arranger view respectively.

```
<SysexCallback>
  f0002029020e00040000f7
</SysexCallback>
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<MidiCallback>
  176: 101, 0
</MidiCallback>
<MidiCallback>
  176: 102, 127
</MidiCallback>
<SysexCallback>
  f0002029020e00040000f7
</SysexCallback>
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<SysexCallback>
  f0002029020e1903f7
<MidiCallback>
  176: 102, 0
</MidiCallback>
<MidiCallback>
  176: 101, 127
</MidiCallback>
<MidiCallback>
  176: 101, 0
</MidiCallback>
<MidiCallback>
  176: 102, 127
</MidiCallback>
<MidiCallback>
  176: 102, 0
</MidiCallback>
```

**Comment by weskoop** [comment]
Could be a bug on the Bitwig side, hard to say. I would say, submit this as a bug to them.

I haven't had time to post much here, but I'm going to end support for the project since Bitwig is supporting the device properly now—of course anyone is welcome to fork it and run with it.
