### ISSUE TITLE
Script not showing.

### ISSUE THREAD

**Issue by DaKingof** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#31]
I'm having issues with Bitwigs default and hoped I could try this but it seems to not be showing in the options. I'm not sure what to do. I copied the folder into my extensions directory.

I'm on Linux(NixOS).

Edit: I tried driven by moss and really prefer the original setup so thought this might be a little more to my liking.

**Comment by weskoop** [comment]
Needs to go into "My Controller Scripts", not extensions.

From the README:
2. Unzip and copy the Launchpad-Pro-Mk3-for-Bitwig_1.x folder to your Bitwig **My Controller Scripts** location.

**Comment by DaKingof** [comment]
> Needs to go into "My Controller Scripts", not extensions.
> 
> From the README: 2. Unzip and copy the Launchpad-Pro-Mk3-for-Bitwig_1.x folder to your Bitwig **My Controller Scripts** location.

I see! With the language used I guess I assumed you weren't being specific with that name. If it said My Controller Scripts 'folder' instead of 'location' then it would be a bit more clear that it's the folder's name. 

Either way, thanks for the assist.
