### ISSUE TITLE
Record Button Behaviour

### ISSUE THREAD

**Issue by weskoop** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#9]
Background: Novation designed and dedicated LaunchPad Pro to the Clip Launcher in Ableton, Session View. It's integration is even under a button of the same name.

So far this script has followed that thinking, but Bitwig moves beyond this idea, integrating the Clip Launcher _with_ the Arranger Timeline.

Until the last ~20% of development on this script, I had the Record Button attached to the transport Record button in the top bar of Bitwig; it did not toggle Clip Overdub, and honestly it was useless is most situations.

When finalizing the scripts behaviour, i tweaked the record button to bring back focus to the Clip Launcher.

I'm used to thinking of these things in my own head, but now that the script is live, I figured I would think out loud. 

I think there may be some potential to bring back the connection to record button in transports, and maybe arranger overdub, though I'm doubtful.

When I think about performance oriented features, Clip Record and Clip Overdub in the Launcher fall into that bucket, capturing multiple clips, variations, building scenes, and it can all be dont without touching the computer, no context switching. Record and overdub in Arranger timeline feels less like a performance/jam tool and more like a deliberate action to capture longer pieces of audio/midi, which would later then be processed in the Bitwig interface, features like Count-in and the general UI lend itself to moving between interfaces, switching from the computer to the instrument and back.

Do we bother with changing this at all? More code/options means more bugs.

How would it work?
Would it support Arranger Overdub? 
Only toggle the record button?
Is this a Preference Toggle? 
Shift Mode? 
Attached to the Arrange/Mix orientation? (probably bad)

**Comment by weskoop** [comment]
@llgcode I think we are on the same page, I think this will generate more questions from average users, and require more documentation.

If it comes up from others in the future, we can look at bringing this back.

**Comment by weskoop** [comment]
Reopening this, I think Rather than Consider adding Arrange Record Support, We take the behaviour from when in Notes Mode, and put it on the shift functionality. I will think about this morning.

Then Shift+Record will always record into the first empty slot on the selected track, if armed. otherwise Shift+Record will do nothing.

Just pressing Record will Toggle Clip Overdub, as it mostly does now.

**Comment by weskoop** [comment]
Found an issue on Group Tracks, the Record button does not trigger a record. I will log an issue with Bitwig.

**Comment by llgcode** [comment]
Hi @weskoop 

Sorry to disturbed you again on this topic.

Yesterday when I played with the session view, I was asking myself if it will be possible 
 - to record when an empty slot is selected
 - to overdub when a clip is selected
 
But shift record is fine ! :-)
